name: Docker Image CI/CD

on:
  push:
    branches:
      - main
      - 'release/*' # Ça déclenchera aussi la CI pour les branches de release

env:
  REGISTRY: sio.jbdelasalle.com
  IMAGE_NAME: kpanuiczka/BEER-KINGDOM

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      # Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuration de Java (JDK 21)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Construction de l'application avec Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Connexion au registre Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Ajouter le certificat de confiance pour le registre
      - name: Add registry certificate
        run: |
          echo "${{ secrets.DOMAINE_CERTIFICAT }}" > /usr/local/share/ca-certificates/registry_cert.crt
          sudo update-ca-certificates
