name: Docker Image CI/CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: registry.sio.jbdelasalle.com
  IMAGE_NAME: kpanuiczka/beer-kingdom

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuration de Java (JDK 21)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      # Installation du certificat du registre Docker privé
      - name: Install registry certificate
        run: |
          echo "$REGISTRY_CERTIFICATE" | sudo tee /usr/local/share/ca-certificates/registry-cert.crt
          sudo update-ca-certificates
        env:
          REGISTRY_CERTIFICATE: ${{ secrets.CERT_SIO }}

      # Redémarrage de Docker pour appliquer le certificat
      - name: Restart Docker to apply certificate
        run: sudo systemctl restart docker

      # Construction de l'application avec Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Vérification du contenu du dossier target/
      - name: List Maven target directory
        run: ls -l target/

      # Connexion au registre Docker
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construction de l'image Docker
      - name: Build Docker Image
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # Push de l'image Docker vers le registre
      - name: Push Docker Image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      